# Generated by Django 4.2.1 on 2024-06-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('education', models.TextField(max_length=5000)),
                ('experience', models.TextField(max_length=5000)),
                ('skills', models.TextField(max_length=1000)),
            ],
        ),
    ]
