# Generated by Django 4.2.1 on 2024-07-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='block',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='resume',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='house_number',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='languages',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='projects',
            field=models.TextField(default=None, max_length=5000),
        ),
        migrations.AddField(
            model_name='resume',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(max_length=5000),
        ),
    ]
